### ISSUE TITLE
Very basic question about configuration

### ISSUE THREAD

**Issue by john-lee-johnson** [WolfgangMehner/perl-support#2]
Hello,

I am new to Vim and having trouble getting this to work with neovim probably because of the default directory differences. I used vim-plug to install perl-support which has installed it under `~/.config/nvim/plugged` instead of the usual `~/.vim` directory mentioned in the readme. However, when I type `<leader>n` it says `E486: Pattern not found: Perl_LoadMenus` It seems I can't seem to get neovim to look in the right directory for perl-support even after including symlinks in ~/.vim to the locations of the directories under `~/.config/nvim/plugged` and have included the following in my neovim config file:

```
filetype plugin on
let g:Perl_GlobalTemplateFile = '~/.config/nvim/plugged/perl-support/perl-support/templates/Templates'
```
I would appreciate any assistance, thank you so much

**Comment by WolfgangMehner** [comment]
Does `~/.config/nvim/plugged/perl-support` appear on your runtimepath? Run this on your Vim cmd.-line:

    :set rtp?

Additionally, what is `<Leader>n` supposed to do? As far as I remember this is not a map perl-support provides.
Lastly, check the output of `:scriptnames` for perl-support.

**Comment by john-lee-johnson** [comment]
Oh I see, I figured it out now, I was not running `\ntw`, I thought '\' was '<Leader>', if I actually type `\ntw` the menu pops up correctly.

Thank you so much
