### ISSUE TITLE
disable template request

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [WolfgangMehner/perl-support#4]
Please explain how to disable the request to update  the templates. I don't need them :-)

Or add an option to disable them like *forever*.

**Comment by g-i-o-r-g-i-o** [comment]
I've been using perl-support for years, and each time there is the same problem.... why?

**Comment by g-i-o-r-g-i-o** [comment]
Hello?

**Comment by WolfgangMehner** [comment]
Sorry, GitHub did not alert me to this issue.

Which version are you referring to? The one from www.vim.org (version `5.4`) or the one published in this repository (currently `5.5pre`)?

**Comment by WolfgangMehner** [comment]
Sorry about the wait, GitHub did not alert me to this issue.

Which version are you  referring to? The one from www.vim.org (version `5.4`) or the one published in this repository (currently `5.5pre`)?

**Comment by g-i-o-r-g-i-o** [comment]
Hello, thanks for your answer, github channel, latest version.

Il giorno lun 22 ott 2018 alle ore 16:49 Wolfgang Mehner <
notifications@github.com> ha scritto:
