### ISSUE TITLE
Disabling of mapping

### ISSUE THREAD

**Issue by mowgli** [WolfgangMehner/perl-support#5]
Hi,

I like your perl-support very much and use it on a daily base.

However, there is one think, that is annoying. It is that mappings cannot be removed again. I have F9 mapped to switch of highlighting and as I use that much, I always end in the debugger that I do not want.

I tried to disable the mapping (unmap <buffer> <F9>) in the after section of vim. But there, the mapping seems to be not existing. It gets created much later. (I don't know when exactly but later than the after directory)

Is there a way to just delete one mapping without changing the source (I do like to stay updatable)?

**Comment by WolfgangMehner** [comment]
I know about this issue, and I know that the current situation is undesirable. I already dealt with it for some of the other projects, e.g. https://github.com/WolfgangMehner/bash-support/commit/e1969c3dedadf1d3cf4be6db4daa3dfda9e2169b

I'll get back to you with a solution where all the F9 mappings are removed and you can define your own ones for these features. This will also ensure forward compatibility.

You will then have to define mappings for these features yourself, using your ftplugin:
```
   Shift-F1   read perldoc  (for the word under the cursor)
         F9   start a debugger
     Alt-F9   run syntax check
    Ctrl-F9   run script
   Shift-F9   set command line arguments (buffer related)
```

You will find examples in `perl-support/rc/*.vim` .

**Comment by WolfgangMehner** [comment]
Since I do not know Perl well, I could need your help with one question:

Which of these five features listed above should have maps for the POD filetype? I mainly ask so I can provide sensible examples in `perl-support/rc/pod.vim`

**Comment by mowgli** [comment]
The only I could think about is the syntax check. pod is only documentation. There should be nothing to run.

**Comment by WolfgangMehner** [comment]
I just pushed e14a382c60207355e3f0a4eec716520ab45cf8b6 .

As I said, it removes all F1 and F9 maps, and adds ex-commands to recreate them. Check out the example map definitions in `perl-support/rc/perl.vim`, and add them to your filetype plug-ins as needed.

Bonus features:

You can give arguments to the script if you use `:Perl`:

    :Perl aa bb cc

You can also give arguments when debugging a script:

    :PerlDebug x y z

You can search for help by adding a topic to the `:PerlDoc` command:

    :PerlDoc print

**Comment by mowgli** [comment]
Works well, thanks.
